### ISSUE TITLE
Healthbar Text not editable

### ISSUE THREAD

**Issue by ujellyx** [Schaka/ArenaLive-WOTLK#8]
The Healthbar Text isn't editable. Changes to the font-size and to the shown Healthbar Text won't apply - no matter which Unit Frame i choose.

Is it somehow possible to change these values in the LUA itself?

**Comment by Schaka** [comment]
You can probably just edit the XML. I haven't touched these UF in in 4 years, so I have absolutely no clue. I might port them for Classic or TBC when it comes out so we shall see then.

**Comment by vendethiel** [comment]
Not sure if ArenaLive makes sense for Vanilla..:)

**Comment by Schaka** [comment]
People use it in TBC where arena units (and arena frames) don't exist too. Meaning they just want the decent frames (for party reasons as well), not necessarily arena frames.

**Comment by vendethiel** [comment]
Oh, for TBC, for sure. I work on Gladius EX for retail and I agree with the party frames thing too. It's still annoying: they made sure, at least for the beta, that the events sent are not helpful i.e. for castbars.
If you wish to recreate your Gladdy's trinket detection then you just have more patience than I do...

**Comment by Schaka** [comment]
I have no idea what the API is like on beta because I have no access to it. But if COMBAT_LOG_EVENT_UNFILITERED exists anywhere close to what it looks like in TBC, it should be easy enough to recreate TrinketTracker. 

The code is a mess and I'd have to start from scratch, especially with categorization which makes much more sense as bitmasks. But the logic is largely the same. 

You know how long an aura is supposed to last, you get an event that it breaks earlier than expected, you check most recently cached combat log events to confirm that the break was not one caused by any other spell through timestamps.

Even in classic, this should be possible. There are already addons for vanilla with fairly accurate timers (through hooking UseAction, CastSpellByName, macros etc) on top of combat log events.

There was a really good Chinese addon (forgot the name - think it's SpellTimer) that did this really well. Based on that and my EnemyBuffTimersVanilla, [ccwatch](https://github.com/shirsig/ccwatch) and [DebuffTimers](https://github.com/Voidmenull/DebuffTimers) were created.

With all of those already right there, you just need to switch out the data source to whatever the Classic beta uses and make it a public API that TrinketTracker could also access (i.e. UnitDebuff being hooked and adding additional parameters similar to what BuffLib does).

**Comment by vendethiel** [comment]
Classic is a fork of the retail client, and they removed a lot of its features, like CastSpellByName being unprotected

**Comment by Schaka** [comment]
I know. They adjusted the API between 7.x and 8x. So I don't know what it actually looks like. 
You could still hook CastSpellByName because it's called by macros and buttons internally. You'd need that for accurate timers. Might have to use hooksecurefunc of the WoW API instead of traditional hooking, but that's it.
